name: Docker build & push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      matrix:
        image:
          - title: "gitpod/workspace-full + terraform"
            description: "The gitpod/workspace-full:latest image with various terraform versions added (see tfenv list)"
            context: "gitpod-terraform"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: awendland/${{ matrix.image.context }}
          tags: |
            type=sha
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=${{ matrix.image.title }}
            org.opencontainers.image.description=${{ matrix.image.description }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}